### ISSUE TITLE
RFE: _htmlDefaultPage should be a public field, ideally also configurable via jarvis.json

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/Jarvis#26]
And if empty, any requests that would return the defaultPage should return a 404. (minimal processing to avoid too much CPU load through "invalid activity")

**Comment by bpbecker** [comment]
This enhancement isn't necessary because you can already achieve the same effect using HTMLInterface.  You can set HTMLInterface to either:

-  a folder - in which case Jarvis expects the home page to be index.html
-  a file - in which case Jarvis uses this file as the default home page
