### ISSUE TITLE
Simpler `sint`

### ISSUE THREAD

**Issue by MaxCan-Code** [Dyalog/Jarvis#59]
https://github.com/Dyalog/Jarvis/blob/4c23d762715c797e0bf8e9320c422fd4545238d0/Source/Jarvis.dyalog#L1723
can be simplified to
```apl
sint←{⎕IO←0 ⋄ 83=⎕DR ⍵:⍵ ⋄ ((⍳,-+⍳)128)[utf8 ⍵]}
```

same goes for HttpCommand:
https://github.com/Dyalog/HttpCommand/blob/2659ea89357f85cbe10d38797500c629c1f2cb8b/source/HttpCommand.dyalog#L958

**Comment by bpbecker** [comment]
Hi Max, 

I appreciate your suggestion!

- I'll put forth that yours is shorter, not necessarily simpler 😃 (the current implementation does fewer operations)
- Yours is slower for arguments <1K. The performance draws even with arguments of around 100K (at least in my very quick and limited testing).  This is probably explained by the computation of (⍳,-+⍳) taking less of the overall time with larger arguments.

So, in this case, I think I'll leave things as they are. (but I do like your solution!)

/Brian
